var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":120,"id":1602,"methods":[{"el":64,"sc":5,"sl":42},{"el":70,"sc":5,"sl":66},{"el":76,"sc":5,"sl":72},{"el":82,"sc":5,"sl":78},{"el":95,"sc":5,"sl":84},{"el":111,"sc":5,"sl":97},{"el":118,"sc":5,"sl":113}],"name":"SkinConfigToolTest","sl":32}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":72}],"name":"testNot","pass":true,"statements":[{"sl":74},{"sl":75}]},"test_15":{"methods":[{"sl":66}],"name":"testIs","pass":true,"statements":[{"sl":68},{"sl":69}]},"test_2":{"methods":[{"sl":113}],"name":"testSlugFilename","pass":true,"statements":[{"sl":115},{"sl":116},{"sl":117}]},"test_32":{"methods":[{"sl":78}],"name":"testIsValue","pass":true,"statements":[{"sl":80},{"sl":81}]},"test_6":{"methods":[{"sl":97}],"name":"testIsExternalLink","pass":true,"statements":[{"sl":100},{"sl":101},{"sl":102},{"sl":103},{"sl":104},{"sl":106},{"sl":107},{"sl":108}]},"test_8":{"methods":[{"sl":84}],"name":"testIsActiveLink","pass":true,"statements":[{"sl":87},{"sl":88},{"sl":89},{"sl":91},{"sl":92},{"sl":93},{"sl":94}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [15], [], [15], [15], [], [], [0], [], [0], [0], [], [], [32], [], [32], [32], [], [], [8], [], [], [8], [8], [8], [], [8], [8], [8], [8], [], [], [6], [], [], [6], [6], [6], [6], [6], [], [6], [6], [6], [], [], [], [], [2], [], [2], [2], [2], [], [], []]