var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":98,"id":2364,"methods":[{"el":32,"sc":5,"sl":29},{"el":42,"sc":5,"sl":34},{"el":52,"sc":5,"sl":44},{"el":58,"sc":5,"sl":54},{"el":64,"sc":5,"sl":60},{"el":75,"sc":5,"sl":66},{"el":89,"sc":5,"sl":77},{"el":96,"sc":5,"sl":91}],"name":"Xpp3UtilsTest","sl":27}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_10":{"methods":[{"sl":77}],"name":"shouldChildrenNodesReturnSpecificChildrenNodes","pass":true,"statements":[{"sl":79},{"sl":80},{"sl":81},{"sl":83},{"sl":84},{"sl":87},{"sl":88}]},"test_18":{"methods":[{"sl":54}],"name":"shouldChildrenNodesReturnEmptyListWhenParentIsNull","pass":true,"statements":[{"sl":56},{"sl":57}]},"test_32":{"methods":[{"sl":44}],"name":"shouldChildNodeNotExist","pass":true,"statements":[{"sl":46},{"sl":47},{"sl":48},{"sl":49},{"sl":51}]},"test_33":{"methods":[{"sl":91}],"name":"shouldChildrenNodesReturnEmptyChildrenNodes","pass":true,"statements":[{"sl":93},{"sl":94},{"sl":95}]},"test_55":{"methods":[{"sl":29}],"name":"shouldFirstChildReturnNullWhenParentIsNull","pass":true,"statements":[{"sl":31}]},"test_57":{"methods":[{"sl":34}],"name":"shouldChildNodeExist","pass":true,"statements":[{"sl":36},{"sl":37},{"sl":38},{"sl":39},{"sl":41}]},"test_64":{"methods":[{"sl":60}],"name":"shouldChildrenReturnEmptyListWhenParentIsNull","pass":true,"statements":[{"sl":62},{"sl":63}]},"test_8":{"methods":[{"sl":66}],"name":"shouldChildrenReturnAllChildrenNodes","pass":true,"statements":[{"sl":68},{"sl":69},{"sl":70},{"sl":73},{"sl":74}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [55], [], [55], [], [], [57], [], [57], [57], [57], [57], [], [57], [], [], [32], [], [32], [32], [32], [32], [], [32], [], [], [18], [], [18], [18], [], [], [64], [], [64], [64], [], [], [8], [], [8], [8], [8], [], [], [8], [8], [], [], [10], [], [10], [10], [10], [], [10], [10], [], [], [10], [10], [], [], [33], [], [33], [33], [33], [], [], []]