var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":99,"id":1746,"methods":[{"el":32,"sc":5,"sl":29},{"el":42,"sc":5,"sl":34},{"el":52,"sc":5,"sl":44},{"el":59,"sc":5,"sl":55},{"el":65,"sc":5,"sl":61},{"el":76,"sc":5,"sl":67},{"el":90,"sc":5,"sl":78},{"el":97,"sc":5,"sl":92}],"name":"Xpp3UtilsTest","sl":25}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":61}],"name":"shouldChildrenReturnEmptyListWhenParentIsNull","pass":true,"statements":[{"sl":63},{"sl":64}]},"test_10":{"methods":[{"sl":44}],"name":"shouldChildNodeNotExist","pass":true,"statements":[{"sl":46},{"sl":47},{"sl":48},{"sl":49},{"sl":51}]},"test_30":{"methods":[{"sl":34}],"name":"shouldChildNodeExist","pass":true,"statements":[{"sl":36},{"sl":37},{"sl":38},{"sl":39},{"sl":41}]},"test_34":{"methods":[{"sl":67}],"name":"shouldChildrenReturnAllChildrenNodes","pass":true,"statements":[{"sl":69},{"sl":70},{"sl":71},{"sl":74},{"sl":75}]},"test_45":{"methods":[{"sl":29}],"name":"shouldFirstChildReturnNullWhenParentIsNull","pass":true,"statements":[{"sl":31}]},"test_47":{"methods":[{"sl":92}],"name":"shouldChildrenNodesReturnEmptyChildrenNodes","pass":true,"statements":[{"sl":94},{"sl":95},{"sl":96}]},"test_7":{"methods":[{"sl":78}],"name":"shouldChildrenNodesReturnSpecificChildrenNodes","pass":true,"statements":[{"sl":80},{"sl":81},{"sl":82},{"sl":84},{"sl":85},{"sl":88},{"sl":89}]},"test_8":{"methods":[{"sl":55}],"name":"shouldChildrenNodesReturnEmptyListWhenParentIsNull","pass":true,"statements":[{"sl":57},{"sl":58}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [45], [], [45], [], [], [30], [], [30], [30], [30], [30], [], [30], [], [], [10], [], [10], [10], [10], [10], [], [10], [], [], [], [8], [], [8], [8], [], [], [1], [], [1], [1], [], [], [34], [], [34], [34], [34], [], [], [34], [34], [], [], [7], [], [7], [7], [7], [], [7], [7], [], [], [7], [7], [], [], [47], [], [47], [47], [47], [], [], []]