var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":96,"id":1484,"methods":[{"el":31,"sc":3,"sl":28},{"el":41,"sc":3,"sl":33},{"el":51,"sc":3,"sl":43},{"el":57,"sc":3,"sl":53},{"el":63,"sc":3,"sl":59},{"el":74,"sc":3,"sl":65},{"el":88,"sc":3,"sl":76},{"el":95,"sc":3,"sl":90}],"name":"Xpp3UtilsTest","sl":26}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_12":{"methods":[{"sl":59}],"name":"shouldChildrenReturnEmptyListWhenParentIsNull","pass":true,"statements":[{"sl":61},{"sl":62}]},"test_30":{"methods":[{"sl":53}],"name":"shouldChildrenNodesReturnEmptyListWhenParentIsNull","pass":true,"statements":[{"sl":55},{"sl":56}]},"test_37":{"methods":[{"sl":76}],"name":"shouldChildrenNodesReturnSpecificChildrenNodes","pass":true,"statements":[{"sl":78},{"sl":79},{"sl":80},{"sl":82},{"sl":83},{"sl":86},{"sl":87}]},"test_49":{"methods":[{"sl":65}],"name":"shouldChildrenReturnAllChildrenNodes","pass":true,"statements":[{"sl":67},{"sl":68},{"sl":69},{"sl":72},{"sl":73}]},"test_80":{"methods":[{"sl":33}],"name":"shouldChildNodeExist","pass":true,"statements":[{"sl":35},{"sl":36},{"sl":37},{"sl":38},{"sl":40}]},"test_90":{"methods":[{"sl":43}],"name":"shouldChildNodeNotExist","pass":true,"statements":[{"sl":45},{"sl":46},{"sl":47},{"sl":48},{"sl":50}]},"test_93":{"methods":[{"sl":90}],"name":"shouldChildrenNodesReturnEmptyChildrenNodes","pass":true,"statements":[{"sl":92},{"sl":93},{"sl":94}]},"test_97":{"methods":[{"sl":28}],"name":"shouldFirstChildReturnNullWhenParentIsNull","pass":true,"statements":[{"sl":30}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [97], [], [97], [], [], [80], [], [80], [80], [80], [80], [], [80], [], [], [90], [], [90], [90], [90], [90], [], [90], [], [], [30], [], [30], [30], [], [], [12], [], [12], [12], [], [], [49], [], [49], [49], [49], [], [], [49], [49], [], [], [37], [], [37], [37], [37], [], [37], [37], [], [], [37], [37], [], [], [93], [], [93], [93], [93], [], []]