language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script: ./mvnw clean install -Dmaven.javadoc.skip=true -Dtoolchains.disabled=true --quiet -B
jdk:
  - openjdk8
branches:
  only:
    - master
notifications:
  email:
    - devacfr@mac.com
