#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

set +x -e

service_name="reflow-build"
docker_cmd="docker"
maven_repo_cache="reflow-maven-repo"
image_name="maven:3.6-jdk-8"

source ci/setenv.sh

if [ "$(container_exists ${service_name})" != "" ]; then
    echo "- Remove Container : ${service_name}"
    docker rm $(docker ps -aq --filter name=${service_name} )
fi

if [ "$(volume_exists ${maven_repo_cache})" = "" ]; then
    echo "- Create Volume : ${maven_repo_cache}"
    docker volume create --name ${maven_repo_cache}
fi

${docker_cmd} run -it --rm \
    -v "${PWD}":/usr/src -v ${maven_repo_cache}:/root/.m2 \
    -w /usr/src \
    ${DOCKER_OPTIONS} ${image_name} \
    mvn dependency:resolve

${docker_cmd} run -it --rm --name ${service_name} \
    -v "${PWD}":/usr/src -v ${maven_repo_cache}:/root/.m2 \
    -w /usr/src \
    ${DOCKER_OPTIONS} ${image_name} \
    mvn "$@" -Dtoolchains.disabled=true
