processHistoricalCloverData (  {
  "name": "Reflow Maven Skin",
  "table": [{
    "cols": [      {
        "id": "timestamp",
        "label": "Date",
        "type": "date"
      },      {
        "id": "AvgClassesPerFile",
        "label": "Avg Classes / File",
        "type": "number"
      },      {
        "id": "AvgMethodComplexity",
        "label": "Average Method Complexity",
        "type": "number"
      },      {
        "id": "AvgMethodsPerClass",
        "label": "Avg Methods / Class",
        "type": "number"
      },      {
        "id": "AvgStatementsPerMethod",
        "label": "Avg Statements / Method",
        "type": "number"
      },      {
        "id": "Complexity",
        "label": "Complexity",
        "type": "number"
      },      {
        "id": "ComplexityDensity",
        "label": "Complexity Density",
        "type": "number"
      },      {
        "id": "ComplexityToCoverage",
        "label": "Complexity / Coverage",
        "type": "number"
      },      {
        "id": "CoveredBranches",
        "label": "Covered Branches",
        "type": "number"
      },      {
        "id": "CoveredElements",
        "label": "Covered Elements",
        "type": "number"
      },      {
        "id": "CoveredMethods",
        "label": "Covered Methods",
        "type": "number"
      },      {
        "id": "CoveredStatements",
        "label": "Covered Statements",
        "type": "number"
      },      {
        "id": "FilteredElements",
        "label": "% Filtered",
        "type": "number"
      },      {
        "id": "LineCount",
        "label": "Lines",
        "type": "number"
      },      {
        "id": "NcLineCount",
        "label": "NC Lines",
        "type": "number"
      },      {
        "id": "PercentageCoveredContribution",
        "label": "% Covered Contribution",
        "type": "number"
      },      {
        "id": "PercentageUncoveredContribution",
        "label": "% Uncovered Contribution",
        "type": "number"
      },      {
        "id": "TotalBranches",
        "label": "Total Branches",
        "type": "number"
      },      {
        "id": "TotalChildren",
        "label": "children",
        "type": "number"
      },      {
        "id": "TotalClasses",
        "label": "Total Classes",
        "type": "number"
      },      {
        "id": "TotalElements",
        "label": "Total Elements",
        "type": "number"
      },      {
        "id": "TotalFiles",
        "label": "Total Files",
        "type": "number"
      },      {
        "id": "TotalMethods",
        "label": "Total Methods",
        "type": "number"
      },      {
        "id": "TotalPackages",
        "label": "Total Packages",
        "type": "number"
      },      {
        "id": "TotalPercentageCovered",
        "label": "% TOTAL Coverage",
        "type": "number"
      },      {
        "id": "TotalStatements",
        "label": "Total Statements",
        "type": "number"
      },      {
        "id": "UncoveredBranches",
        "label": "Uncovered Branches",
        "type": "number"
      },      {
        "id": "UncoveredElements",
        "label": "Uncovered Elements",
        "type": "number"
      },      {
        "id": "UncoveredMethods",
        "label": "Uncovered Methods",
        "type": "number"
      },      {
        "id": "UncoveredStatements",
        "label": "Uncovered Statements",
        "type": "number"
      }    ],
    "rows": [      {"c": [        {
          "f": "20/01/2026 12:24",
          "v": new Date(1768908291969)
        },        {
          "f": "1,35",
          "v": 1.3513514
        },        {
          "f": "2,05",
          "v": 2.0514905
        },        {
          "f": "7,38",
          "v": 7.38
        },        {
          "f": "4,7",
          "v": 4.704607
        },        {
          "f": "757",
          "v": 757
        },        {
          "f": "0,44",
          "v": 0.43605992
        },        {
          "f": "1\u202f042",
          "v": 1042
        },        {
          "f": "379",
          "v": 379
        },        {
          "f": "1\u202f986",
          "v": 1986
        },        {
          "f": "274",
          "v": 274
        },        {
          "f": "1\u202f333",
          "v": 1333
        },        {
          "f": " - ",
          "v": -100
        },        {
          "f": "8\u202f021",
          "v": 8021
        },        {
          "f": "3\u202f980",
          "v": 3980
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "630",
          "v": 630
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "50",
          "v": 50
        },        {
          "f": "2\u202f735",
          "v": 2735
        },        {
          "f": "37",
          "v": 37
        },        {
          "f": "369",
          "v": 369
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "72,6%",
          "v": 72.61426
        },        {
          "f": "1\u202f736",
          "v": 1736
        },        {
          "f": "251",
          "v": 251
        },        {
          "f": "749",
          "v": 749
        },        {
          "f": "95",
          "v": 95
        },        {
          "f": "403",
          "v": 403
        }      ]},      {"c": [        {
          "f": "20/01/2026 12:25",
          "v": new Date(1768908346767)
        },        {
          "f": "1,35",
          "v": 1.3513514
        },        {
          "f": "2,05",
          "v": 2.0514905
        },        {
          "f": "7,38",
          "v": 7.38
        },        {
          "f": "4,7",
          "v": 4.704607
        },        {
          "f": "757",
          "v": 757
        },        {
          "f": "0,44",
          "v": 0.43605992
        },        {
          "f": "1\u202f042",
          "v": 1042
        },        {
          "f": "379",
          "v": 379
        },        {
          "f": "1\u202f986",
          "v": 1986
        },        {
          "f": "274",
          "v": 274
        },        {
          "f": "1\u202f333",
          "v": 1333
        },        {
          "f": " - ",
          "v": -100
        },        {
          "f": "8\u202f021",
          "v": 8021
        },        {
          "f": "3\u202f980",
          "v": 3980
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "630",
          "v": 630
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "50",
          "v": 50
        },        {
          "f": "2\u202f735",
          "v": 2735
        },        {
          "f": "37",
          "v": 37
        },        {
          "f": "369",
          "v": 369
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "72,6%",
          "v": 72.61426
        },        {
          "f": "1\u202f736",
          "v": 1736
        },        {
          "f": "251",
          "v": 251
        },        {
          "f": "749",
          "v": 749
        },        {
          "f": "95",
          "v": 95
        },        {
          "f": "403",
          "v": 403
        }      ]},      {"c": [        {
          "f": "20/01/2026 12:26",
          "v": new Date(1768908375531)
        },        {
          "f": "1,35",
          "v": 1.3513514
        },        {
          "f": "2,05",
          "v": 2.0514905
        },        {
          "f": "7,38",
          "v": 7.38
        },        {
          "f": "4,7",
          "v": 4.704607
        },        {
          "f": "757",
          "v": 757
        },        {
          "f": "0,44",
          "v": 0.43605992
        },        {
          "f": "1\u202f042",
          "v": 1042
        },        {
          "f": "379",
          "v": 379
        },        {
          "f": "1\u202f986",
          "v": 1986
        },        {
          "f": "274",
          "v": 274
        },        {
          "f": "1\u202f333",
          "v": 1333
        },        {
          "f": " - ",
          "v": -100
        },        {
          "f": "8\u202f021",
          "v": 8021
        },        {
          "f": "3\u202f980",
          "v": 3980
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "630",
          "v": 630
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "50",
          "v": 50
        },        {
          "f": "2\u202f735",
          "v": 2735
        },        {
          "f": "37",
          "v": 37
        },        {
          "f": "369",
          "v": 369
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "72,6%",
          "v": 72.61426
        },        {
          "f": "1\u202f736",
          "v": 1736
        },        {
          "f": "251",
          "v": 251
        },        {
          "f": "749",
          "v": 749
        },        {
          "f": "95",
          "v": 95
        },        {
          "f": "403",
          "v": 403
        }      ]},      {"c": [        {
          "f": "20/01/2026 12:32",
          "v": new Date(1768908742884)
        },        {
          "f": "1,35",
          "v": 1.3513514
        },        {
          "f": "2,05",
          "v": 2.0514905
        },        {
          "f": "7,38",
          "v": 7.38
        },        {
          "f": "4,7",
          "v": 4.704607
        },        {
          "f": "757",
          "v": 757
        },        {
          "f": "0,44",
          "v": 0.43605992
        },        {
          "f": "1\u202f042",
          "v": 1042
        },        {
          "f": "379",
          "v": 379
        },        {
          "f": "1\u202f986",
          "v": 1986
        },        {
          "f": "274",
          "v": 274
        },        {
          "f": "1\u202f333",
          "v": 1333
        },        {
          "f": " - ",
          "v": -100
        },        {
          "f": "8\u202f021",
          "v": 8021
        },        {
          "f": "3\u202f980",
          "v": 3980
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "630",
          "v": 630
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "50",
          "v": 50
        },        {
          "f": "2\u202f735",
          "v": 2735
        },        {
          "f": "37",
          "v": 37
        },        {
          "f": "369",
          "v": 369
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "72,6%",
          "v": 72.61426
        },        {
          "f": "1\u202f736",
          "v": 1736
        },        {
          "f": "251",
          "v": 251
        },        {
          "f": "749",
          "v": 749
        },        {
          "f": "95",
          "v": 95
        },        {
          "f": "403",
          "v": 403
        }      ]},      {"c": [        {
          "f": "20/01/2026 12:32",
          "v": new Date(1768908771495)
        },        {
          "f": "1,35",
          "v": 1.3513514
        },        {
          "f": "2,05",
          "v": 2.0514905
        },        {
          "f": "7,38",
          "v": 7.38
        },        {
          "f": "4,7",
          "v": 4.704607
        },        {
          "f": "757",
          "v": 757
        },        {
          "f": "0,44",
          "v": 0.43605992
        },        {
          "f": "1\u202f042",
          "v": 1042
        },        {
          "f": "379",
          "v": 379
        },        {
          "f": "1\u202f986",
          "v": 1986
        },        {
          "f": "274",
          "v": 274
        },        {
          "f": "1\u202f333",
          "v": 1333
        },        {
          "f": " - ",
          "v": -100
        },        {
          "f": "8\u202f021",
          "v": 8021
        },        {
          "f": "3\u202f980",
          "v": 3980
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "100%",
          "v": 100
        },        {
          "f": "630",
          "v": 630
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "50",
          "v": 50
        },        {
          "f": "2\u202f735",
          "v": 2735
        },        {
          "f": "37",
          "v": 37
        },        {
          "f": "369",
          "v": 369
        },        {
          "f": "4",
          "v": 4
        },        {
          "f": "72,6%",
          "v": 72.61426
        },        {
          "f": "1\u202f736",
          "v": 1736
        },        {
          "f": "251",
          "v": 251
        },        {
          "f": "749",
          "v": 749
        },        {
          "f": "95",
          "v": 95
        },        {
          "f": "403",
          "v": 403
        }      ]}    ]
  }]
}
 ); 