var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":96,"id":3347,"methods":[{"el":91,"sc":3,"sl":47},{"el":95,"sc":3,"sl":93}],"name":"BaseSnippetTest","sl":33}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_11":{"methods":[{"sl":93}],"name":"shouldNotDisplayDate","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_16":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_23":{"methods":[{"sl":93}],"name":"shouldRenderNestedComponent","pass":true,"statements":[{"sl":94}]},"test_26":{"methods":[{"sl":93}],"name":"shouldDisplayButtonToolbar","pass":true,"statements":[{"sl":94}]},"test_29":{"methods":[{"sl":93}],"name":"shouldRenderBadge","pass":true,"statements":[{"sl":94}]},"test_39":{"methods":[{"sl":93}],"name":"shouldContainSnippetComponent","pass":true,"statements":[{"sl":94}]},"test_49":{"methods":[{"sl":93}],"name":"shouldReplaceSnippetByHtml","pass":true,"statements":[{"sl":94}]},"test_57":{"methods":[{"sl":93}],"name":"shouldRenderGroupButton","pass":true,"statements":[{"sl":94}]},"test_58":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_64":{"methods":[{"sl":93}],"name":"shouldRenderDebug","pass":true,"statements":[{"sl":94}]},"test_66":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_68":{"methods":[{"sl":93}],"name":"shouldNotDisplayDateForUnrecognizedPosition","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_7":{"methods":[{"sl":93}],"name":"shouldRenderLayout","pass":true,"statements":[{"sl":94}]},"test_83":{"methods":[{"sl":93}],"name":"shouldRenderCard","pass":true,"statements":[{"sl":94}]},"test_92":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_93":{"methods":[{"sl":93}],"name":"shouldRenderCardRecursively","pass":true,"statements":[{"sl":94}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [58, 16, 66, 92, 11, 68], [58, 16, 66, 92, 11, 68], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [57, 26, 93, 58, 64, 49, 16, 23, 66, 7, 92, 83, 11, 29, 68, 39], [57, 26, 93, 58, 64, 49, 16, 23, 66, 7, 92, 83, 11, 29, 68, 39], [], []]