var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":117,"id":3473,"methods":[{"el":29,"sc":3,"sl":25},{"el":38,"sc":3,"sl":31},{"el":49,"sc":3,"sl":40},{"el":60,"sc":3,"sl":51},{"el":71,"sc":3,"sl":62},{"el":82,"sc":3,"sl":73},{"el":93,"sc":3,"sl":84},{"el":104,"sc":3,"sl":95},{"el":115,"sc":3,"sl":106}],"name":"SnippetParserTest","sl":23}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_23":{"methods":[{"sl":106}],"name":"shouldRenderNestedComponent","pass":true,"statements":[{"sl":108},{"sl":109},{"sl":110}]},"test_29":{"methods":[{"sl":84}],"name":"shouldRenderBadge","pass":true,"statements":[{"sl":86},{"sl":87},{"sl":88}]},"test_39":{"methods":[{"sl":31}],"name":"shouldContainSnippetComponent","pass":true,"statements":[{"sl":33},{"sl":34},{"sl":35},{"sl":36},{"sl":37}]},"test_49":{"methods":[{"sl":40}],"name":"shouldReplaceSnippetByHtml","pass":true,"statements":[{"sl":42},{"sl":43},{"sl":44}]},"test_64":{"methods":[{"sl":62}],"name":"shouldRenderDebug","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":66}]},"test_7":{"methods":[{"sl":95}],"name":"shouldRenderLayout","pass":true,"statements":[{"sl":97},{"sl":98},{"sl":99}]},"test_83":{"methods":[{"sl":51}],"name":"shouldRenderCard","pass":true,"statements":[{"sl":53},{"sl":54},{"sl":55}]},"test_93":{"methods":[{"sl":73}],"name":"shouldRenderCardRecursively","pass":true,"statements":[{"sl":75},{"sl":76},{"sl":77}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [39], [], [39], [39], [39], [39], [39], [], [], [49], [], [49], [49], [49], [], [], [], [], [], [], [83], [], [83], [83], [83], [], [], [], [], [], [], [64], [], [64], [64], [64], [], [], [], [], [], [], [93], [], [93], [93], [93], [], [], [], [], [], [], [29], [], [29], [29], [29], [], [], [], [], [], [], [7], [], [7], [7], [7], [], [], [], [], [], [], [23], [], [23], [23], [23], [], [], [], [], [], [], []]