var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":96,"id":3212,"methods":[{"el":91,"sc":3,"sl":47},{"el":95,"sc":3,"sl":93}],"name":"BaseSnippetTest","sl":33}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":93}],"name":"shouldDisplayButtonToolbar","pass":true,"statements":[{"sl":94}]},"test_100":{"methods":[{"sl":93}],"name":"shouldRenderCard","pass":true,"statements":[{"sl":94}]},"test_29":{"methods":[{"sl":93}],"name":"shouldRenderBadge","pass":true,"statements":[{"sl":94}]},"test_32":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_35":{"methods":[{"sl":93}],"name":"shouldRenderLayout","pass":true,"statements":[{"sl":94}]},"test_36":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_42":{"methods":[{"sl":93}],"name":"shouldRenderNestedComponent","pass":true,"statements":[{"sl":94}]},"test_68":{"methods":[{"sl":93}],"name":"shouldRenderGroupButton","pass":true,"statements":[{"sl":94}]},"test_73":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_77":{"methods":[{"sl":93}],"name":"shouldContainSnippetComponent","pass":true,"statements":[{"sl":94}]},"test_79":{"methods":[{"sl":93}],"name":"shouldNotDisplayDateForUnrecognizedPosition","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_82":{"methods":[{"sl":93}],"name":"shouldRenderDebug","pass":true,"statements":[{"sl":94}]},"test_83":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_88":{"methods":[{"sl":93}],"name":"shouldReplaceSnippetByHtml","pass":true,"statements":[{"sl":94}]},"test_94":{"methods":[{"sl":93}],"name":"shouldNotDisplayDate","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_99":{"methods":[{"sl":93}],"name":"shouldRenderCardRecursively","pass":true,"statements":[{"sl":94}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [36, 94, 83, 73, 79, 32], [36, 94, 83, 73, 79, 32], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [36, 0, 94, 83, 73, 29, 79, 82, 99, 88, 35, 42, 100, 77, 68, 32], [36, 0, 94, 83, 73, 29, 79, 82, 99, 88, 35, 42, 100, 77, 68, 32], [], []]