var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":96,"id":3246,"methods":[{"el":91,"sc":3,"sl":47},{"el":95,"sc":3,"sl":93}],"name":"BaseSnippetTest","sl":33}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_10":{"methods":[{"sl":93}],"name":"shouldRenderCard","pass":true,"statements":[{"sl":94}]},"test_101":{"methods":[{"sl":93}],"name":"shouldRenderDebug","pass":true,"statements":[{"sl":94}]},"test_12":{"methods":[{"sl":93}],"name":"shouldReplaceSnippetByHtml","pass":true,"statements":[{"sl":94}]},"test_15":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_18":{"methods":[{"sl":93}],"name":"shouldRenderLayout","pass":true,"statements":[{"sl":94}]},"test_19":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_21":{"methods":[{"sl":93}],"name":"shouldNotDisplayDateForUnrecognizedPosition","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_3":{"methods":[{"sl":93}],"name":"shouldRenderBadge","pass":true,"statements":[{"sl":94}]},"test_33":{"methods":[{"sl":93}],"name":"shouldRenderCardRecursively","pass":true,"statements":[{"sl":94}]},"test_47":{"methods":[{"sl":93}],"name":"shouldRenderGroupButton","pass":true,"statements":[{"sl":94}]},"test_50":{"methods":[{"sl":93}],"name":"shouldContainSnippetComponent","pass":true,"statements":[{"sl":94}]},"test_67":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_73":{"methods":[{"sl":93}],"name":"shouldRenderRecursively","pass":true,"statements":[{"sl":94}]},"test_89":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_91":{"methods":[{"sl":93}],"name":"shouldRenderNestedComponent","pass":true,"statements":[{"sl":94}]},"test_94":{"methods":[{"sl":93}],"name":"shouldDisplayButtonToolbar","pass":true,"statements":[{"sl":94}]},"test_97":{"methods":[{"sl":93}],"name":"shouldNotDisplayDate","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [19, 15, 67, 97, 89, 21], [19, 15, 67, 97, 89, 21], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [47, 101, 19, 94, 18, 15, 50, 91, 67, 97, 10, 12, 89, 33, 21, 73, 3], [47, 101, 19, 94, 18, 15, 50, 91, 67, 97, 10, 12, 89, 33, 21, 73, 3], [], []]