var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":69,"id":1041,"methods":[{"el":52,"sc":5,"sl":47},{"el":61,"sc":5,"sl":59},{"el":68,"sc":5,"sl":66}],"name":"PageContext","sl":33}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":47}],"name":"shouldReplaceIcons","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51}]},"test_12":{"methods":[{"sl":47},{"sl":66}],"name":"shouldBuildPageContextWithTocDisabled","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51},{"sl":67}]},"test_15":{"methods":[{"sl":47}],"name":"shouldReplaceTTTag","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51}]},"test_17":{"methods":[{"sl":47}],"name":"shouldAddLighboxAttribute","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51}]},"test_45":{"methods":[{"sl":47}],"name":"shouldNotChangeCodePart","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51}]},"test_8":{"methods":[{"sl":47},{"sl":66}],"name":"shouldBuildPageContext","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51},{"sl":67}]},"test_82":{"methods":[{"sl":47}],"name":"shouldApplyBootstrapCss","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":51}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [17, 8, 1, 45, 12, 82, 15], [17, 8, 1, 45, 12, 82, 15], [17, 8, 1, 45, 12, 82, 15], [17, 8, 1, 45, 12, 82, 15], [17, 8, 1, 45, 12, 82, 15], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [8, 12], [8, 12], [], []]