var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":96,"id":3246,"methods":[{"el":91,"sc":3,"sl":47},{"el":95,"sc":3,"sl":93}],"name":"BaseSnippetTest","sl":33}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":93}],"name":"shouldRenderCardRecursively","pass":true,"statements":[{"sl":94}]},"test_16":{"methods":[{"sl":93}],"name":"shouldRenderRecursively","pass":true,"statements":[{"sl":94}]},"test_20":{"methods":[{"sl":93}],"name":"shouldRenderDebug","pass":true,"statements":[{"sl":94}]},"test_3":{"methods":[{"sl":93}],"name":"shouldRenderCard","pass":true,"statements":[{"sl":94}]},"test_31":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_33":{"methods":[{"sl":93}],"name":"shouldDisplayButtonToolbar","pass":true,"statements":[{"sl":94}]},"test_35":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_36":{"methods":[{"sl":93}],"name":"shouldRenderBadge","pass":true,"statements":[{"sl":94}]},"test_4":{"methods":[{"sl":93}],"name":"shouldNotDisplayDateForUnrecognizedPosition","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_42":{"methods":[{"sl":93}],"name":"shouldReplaceSnippetByHtml","pass":true,"statements":[{"sl":94}]},"test_45":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_57":{"methods":[{"sl":93}],"name":"shouldContainSnippetComponent","pass":true,"statements":[{"sl":94}]},"test_69":{"methods":[{"sl":93}],"name":"shouldRenderLayout","pass":true,"statements":[{"sl":94}]},"test_73":{"methods":[{"sl":93}],"name":"shouldNotDisplayDate","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_81":{"methods":[{"sl":93}],"name":"shouldRenderNestedComponent","pass":true,"statements":[{"sl":94}]},"test_82":{"methods":[{"sl":93}],"name":"shouldRenderGroupButton","pass":true,"statements":[{"sl":94}]},"test_93":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [73, 31, 45, 93, 4, 35], [73, 31, 45, 93, 4, 35], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [20, 36, 69, 73, 33, 31, 45, 1, 16, 93, 82, 3, 4, 57, 81, 35, 42], [20, 36, 69, 73, 33, 31, 45, 1, 16, 93, 82, 3, 4, 57, 81, 35, 42], [], []]