var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":96,"id":3246,"methods":[{"el":91,"sc":3,"sl":47},{"el":95,"sc":3,"sl":93}],"name":"BaseSnippetTest","sl":33}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_102":{"methods":[{"sl":93}],"name":"shouldNotDisplayDate","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_17":{"methods":[{"sl":93}],"name":"shouldReplaceSnippetByHtml","pass":true,"statements":[{"sl":94}]},"test_21":{"methods":[{"sl":93}],"name":"shouldRenderLayout","pass":true,"statements":[{"sl":94}]},"test_26":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_32":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToLeft","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_35":{"methods":[{"sl":93}],"name":"shouldRenderCard","pass":true,"statements":[{"sl":94}]},"test_4":{"methods":[{"sl":93}],"name":"shouldRenderRecursively","pass":true,"statements":[{"sl":94}]},"test_46":{"methods":[{"sl":93}],"name":"shouldDisplayVersionPositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_48":{"methods":[{"sl":93}],"name":"shouldRenderBadge","pass":true,"statements":[{"sl":94}]},"test_53":{"methods":[{"sl":93}],"name":"shouldDisplayButtonToolbar","pass":true,"statements":[{"sl":94}]},"test_60":{"methods":[{"sl":93}],"name":"shouldContainSnippetComponent","pass":true,"statements":[{"sl":94}]},"test_63":{"methods":[{"sl":93}],"name":"shouldNotDisplayDateForUnrecognizedPosition","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_68":{"methods":[{"sl":93}],"name":"shouldRenderDebug","pass":true,"statements":[{"sl":94}]},"test_74":{"methods":[{"sl":93}],"name":"shouldRenderCardRecursively","pass":true,"statements":[{"sl":94}]},"test_77":{"methods":[{"sl":93}],"name":"shouldRenderNestedComponent","pass":true,"statements":[{"sl":94}]},"test_85":{"methods":[{"sl":93}],"name":"shouldDisplayDatePositionToRight","pass":true,"statements":[{"sl":64},{"sl":65},{"sl":94}]},"test_94":{"methods":[{"sl":93}],"name":"shouldRenderGroupButton","pass":true,"statements":[{"sl":94}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [102, 32, 26, 46, 85, 63], [102, 32, 26, 46, 85, 63], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [74, 68, 102, 4, 32, 94, 53, 77, 26, 46, 85, 21, 17, 63, 35, 48, 60], [74, 68, 102, 4, 32, 94, 53, 77, 26, 46, 85, 21, 17, 63, 35, 48, 60], [], []]